name: custom_vin_decoder
description:
  Dart library for working with Vehicle Identification Numbers (VINs) based on ISO 3779:2009 and
  World Manufacturer Identifiers (WMIs) based on ISO 3780:2009, enriched by NHTSA data.

version: 0.2.1
repository: https://github.com/adaptant-labs/vin-decoder-dart
issue_tracker: https://github.com/adaptant-labs/vin-decoder-dart/issues

environment:
  sdk: ">=3.3.0 <4.0.0" #'>=2.12.0 <4.0.0' # Important no space allowed between math operator and the numeric digit so < 3 is not the same as <3

dependencies:
  basic_utils: ^5.0.0 #^4.5.2 #^3.4.0
  http: ^1.3.0 #^0.13.6 #^0.13.3
  meta: ^1.16.0 #^1.8.0
  random_string: ^2.2.0-nullsafety
 # test: ^1.25.15

dev_dependencies:
  test: ^1.25.15 #^1.17.5
