name: custom_vin_decoder
description:
  Dart library for working with Vehicle Identification Numbers (VINs) based on ISO 3779:2009 and
  World Manufacturer Identifiers (WMIs) based on ISO 3780:2009, enriched by NHTSA data.

version: 0.2.1
repository: https://github.com/adaptant-labs/vin-decoder-dart
issue_tracker: https://github.com/adaptant-labs/vin-decoder-dart/issues

environment:
  sdk: ">=3.7.2 <4.0.0" #'>=2.12.0 <4.0.0' # Important no space allowed between math operator and the numeric digit so < 3 is not the same as <3

dependencies:
  basic_utils: ^5.8.2 #^4.5.2 #^3.4.0
  http: ^1.5.0 #^0.13.6 #^0.13.3
  meta: ^1.16.0 #^1.8.0
  random_string: ^2.2.0-nullsafety
 # test: ^1.25.15

dev_dependencies:
  _fe_analyzer_shared: ^88.0.0 #Transitive Dependancy based on the sdk version 3.7.2
  analyzer: ^8.1.1 #Transitive Dependancy
  test: ^1.26.3 #^1.25.15
